name: CI
on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  unix:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-11, macos-12]
    

    steps:
      - uses: actions/checkout@v4

      - name: Install micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment-dev.yml
          environment-name: xeus-qt

      - name: Create build directory
        shell: bash -l {0}
        run: mkdir -p build

      - name: cmake configure
        shell: bash -l {0}
        run: |
          cmake .. \
           -DCMAKE_PREFIX_PATH=$CONDA_PREFIX \
           -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX 
        working-directory: build

      - name: build
        shell: bash -l {0}
        run: |
          make -j 2
        working-directory: build
     
      - name: install xeus-qt
        shell: bash -l {0}
        run: |
          make install
        working-directory: build

      - name: install mesa-lib
        shell: bash -l {0}
        run: micromamba install mesalib -c conda-forge

      - name: build example kernel
        shell: bash -l {0}
        run: |
          mkdir -p build
          cd build
          cmake .. \
           -DCMAKE_PREFIX_PATH=$CONDA_PREFIX \
           -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX 
           make -j 2
        working-directory: examples

  win:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2019, windows-2022 ]

    steps:
      - uses: actions/checkout@v4

      - name: install mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment-dev.yml
          environment-name: xeus-qt
          init-shell: cmd.exe

      - name: Make build directory
        run: mkdir build

      - name: cmake configure
        shell: cmd /C call {0}
        run: |
          cmake .. ^
           -G Ninja ^
           -DCMAKE_BUILD_TYPE=Release ^
           -DDEPENDENCY_SEARCH_PREFIX="%CONDA_PREFIX%\Library" ^
           -DCMAKE_PREFIX_PATH="%CONDA_PREFIX%\Library" ^
           -DCMAKE_INSTALL_PREFIX="%CONDA_PREFIX%"
        working-directory: build

      - name: build and install
        shell: cmd /C call {0}
        run: |
          set CL=/MP
          ninja install
        working-directory: build

      - name: build example kernel
        shell: cmd /C call {0}
        run: |
          mkdir -p build
          cd build
          cmake .. ^
           -G Ninja ^
           -DCMAKE_BUILD_TYPE=Release ^
           -DDEPENDENCY_SEARCH_PREFIX="%CONDA_PREFIX%\Library" ^
           -DCMAKE_PREFIX_PATH="%CONDA_PREFIX%\Library" ^
           -DCMAKE_INSTALL_PREFIX="%CONDA_PREFIX%"
          ninja
        working-directory: examples

